// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CockpitHUD.tsx": () => import("../components/mockups/CockpitHUD.tsx"),
  "./components/mockups/EditorialStory.tsx": () => import("../components/mockups/EditorialStory.tsx"),
  "./components/mockups/NeonTerminal.tsx": () => import("../components/mockups/NeonTerminal.tsx"),
  "./components/mockups/appstore/AnalyticsDisplayPreview.tsx": () => import("../components/mockups/appstore/AnalyticsDisplayPreview.tsx"),
  "./components/mockups/appstore/AppStore_CockpitHUD.tsx": () => import("../components/mockups/appstore/AppStore_CockpitHUD.tsx"),
  "./components/mockups/appstore/AppStore_EditorialStory.tsx": () => import("../components/mockups/appstore/AppStore_EditorialStory.tsx"),
  "./components/mockups/appstore/AppStore_NeonTerminal.tsx": () => import("../components/mockups/appstore/AppStore_NeonTerminal.tsx"),
  "./components/mockups/appstore/AppStore_Onb_BlurredPreview.tsx": () => import("../components/mockups/appstore/AppStore_Onb_BlurredPreview.tsx"),
  "./components/mockups/appstore/AppStore_Onb_Building.tsx": () => import("../components/mockups/appstore/AppStore_Onb_Building.tsx"),
  "./components/mockups/appstore/AppStore_Onb_Challenge.tsx": () => import("../components/mockups/appstore/AppStore_Onb_Challenge.tsx"),
  "./components/mockups/appstore/AppStore_Onb_GigApps.tsx": () => import("../components/mockups/appstore/AppStore_Onb_GigApps.tsx"),
  "./components/mockups/appstore/AppStore_Onb_Paywall.tsx": () => import("../components/mockups/appstore/AppStore_Onb_Paywall.tsx"),
  "./components/mockups/appstore/AppStore_Onb_Solution.tsx": () => import("../components/mockups/appstore/AppStore_Onb_Solution.tsx"),
  "./components/mockups/appstore/AppStore_Onb_WeeklyGoal.tsx": () => import("../components/mockups/appstore/AppStore_Onb_WeeklyGoal.tsx"),
  "./components/mockups/appstore/AppStore_Onb_Welcome.tsx": () => import("../components/mockups/appstore/AppStore_Onb_Welcome.tsx"),
  "./components/mockups/onboarding/BlurredPreview.tsx": () => import("../components/mockups/onboarding/BlurredPreview.tsx"),
  "./components/mockups/onboarding/BuildingDashboard.tsx": () => import("../components/mockups/onboarding/BuildingDashboard.tsx"),
  "./components/mockups/onboarding/Challenge.tsx": () => import("../components/mockups/onboarding/Challenge.tsx"),
  "./components/mockups/onboarding/GigApps.tsx": () => import("../components/mockups/onboarding/GigApps.tsx"),
  "./components/mockups/onboarding/Paywall.tsx": () => import("../components/mockups/onboarding/Paywall.tsx"),
  "./components/mockups/onboarding/Solution.tsx": () => import("../components/mockups/onboarding/Solution.tsx"),
  "./components/mockups/onboarding/WeeklyGoal.tsx": () => import("../components/mockups/onboarding/WeeklyGoal.tsx"),
  "./components/mockups/onboarding/Welcome.tsx": () => import("../components/mockups/onboarding/Welcome.tsx")
};
