// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CockpitHUD.tsx": () => import("../components/mockups/CockpitHUD.tsx"),
  "./components/mockups/EditorialStory.tsx": () => import("../components/mockups/EditorialStory.tsx"),
  "./components/mockups/NeonTerminal.tsx": () => import("../components/mockups/NeonTerminal.tsx")
};
