uploads = []
generated = []

[[outputs]]
id = "AHF-530LgLlQZI4QbGeIL"
uri = "file://earnings-ninja-master.zip"
type = "unspecified"
title = "Earnings Ninja - Master Project Files"

[[outputs]]
id = "KIb_13ZVzvqvvYsDGqPIE"
uri = "file://earnings-ninja-ios.zip"
type = "unspecified"
title = "Earnings Ninja - iOS App Store Package"

[[outputs]]
id = "WZfSJ-LCVpKjsi4CXlDEu"
uri = "file://earnings-ninja-expo.zip"
type = "unspecified"
title = "Earnings Ninja - Expo iOS App"

[[outputs]]
id = "x2tSjgn-UBsPDnAEwX5xb"
uri = "file://expo_qr.png"
type = "image"
title = "Expo Go QR Code — exp://kelpojy-anonymous-8081.exp.direct"
