import { useState } from 'react'
import { Link } from '../components/router'
import { AppStoreBadge, Footer, Nav, SectionLabel, StickyCta, WaitlistForm, useDocumentMeta, UpgradeButton } from '../components/ui'
import { PhoneShot, SCREENSHOTS } from '../components/mockups'
import { APP_DOWNLOAD_URL, FAQS, LANDING_FEATURES, PLATFORMS } from '../lib/content'

export default function LandingPage() {
  useDocumentMeta('Earnings Ninja | Stop confusing revenue with profit', 'Know what you actually keep after gas and expenses across every gig app.')
  return <div className="grain min-h-screen text-white"><Nav ctaTo={APP_DOWNLOAD_URL} /><Hero /><Platforms /><Reality /><Workflow /><Outcomes /><Personas /><Calculator /><Pricing /><Faq /><Final /><Footer /><StickyCta label="Start tracking for free" to={APP_DOWNLOAD_URL} /></div>
}

function Hero() {
  return <section id="top" className="relative overflow-hidden border-b border-border">
    <div className="absolute inset-0 grid-bg opacity-40" />
    <div className="relative max-w-6xl mx-auto px-5 pt-16 pb-20 md:pt-28 md:pb-32 grid lg:grid-cols-[1.05fr_.95fr] gap-14 items-center">
      <div className="reveal"><div className="inline-flex tape px-3 py-1 text-xs font-black uppercase tracking-widest mb-7">Built in the front seat</div>
        <h1 className="text-6xl sm:text-7xl md:text-8xl font-black uppercase leading-[.84] tracking-[-.04em]">You made<br /><span className="text-primary">$200 today.</span><br />What did you keep?</h1>
        <p className="mt-7 text-lg md:text-xl text-muted max-w-xl">Track earnings, gas, expenses, goals, and <strong className="text-white">real profit</strong> across DoorDash, Uber Eats, Instacart, Spark, and more—all in one place.</p>
        <div id="waitlist" data-cta className="mt-8"><WaitlistForm source="landing-hero" /></div>
        <div className="mt-5 flex flex-wrap gap-3 items-center"><AppStoreBadge /><span className="text-xs text-muted border border-border rounded-xl px-4 py-3">Google Play<br /><strong className="text-white">Coming soon</strong></span><Link to="/#how" className="text-sm font-bold text-primary px-2">See how it works ↓</Link></div>
        <p className="mono text-[10px] uppercase tracking-widest text-muted mt-6">For drivers, not accountants.</p>
      </div>
      <div className="reveal-delay relative flex justify-center lg:justify-end"><div className="absolute -inset-12 bg-primary/10 blur-3xl rounded-full" /><PhoneShot src={SCREENSHOTS.dashboardDay} alt="Earnings Ninja showing gross earnings, expenses, and actual profit" priority /></div>
    </div>
  </section>
}

function Platforms() { return <section className="border-b border-border bg-surface/40"><div className="max-w-6xl mx-auto px-5 py-7 flex flex-wrap gap-x-7 gap-y-3 items-center"><span className="mono text-xs text-primary uppercase">One dashboard</span>{PLATFORMS.map((p) => <span key={p} className="font-bold text-sm text-muted">{p}</span>)}<span className="font-bold text-sm text-muted">+ custom gigs</span></div></section> }

function Reality() { const rows = [['DoorDash says', '$142 earned', 'Your real profit', '$103 after gas + expenses'], ['Three apps running', 'Three separate totals', 'Earnings Ninja', 'One combined dashboard'], ['Daily goal', 'Somewhere in your head', 'Earnings Ninja', 'Tracked in real time']]; return <section className="py-24 md:py-32"><div className="max-w-6xl mx-auto px-5"><SectionLabel>The apps show revenue. We show reality.</SectionLabel><h2 className="text-5xl md:text-7xl uppercase font-black leading-[.9] max-w-3xl">Stop guessing.<br /><span className="text-primary">Know your numbers.</span></h2><div className="mt-12 border-t border-border">{rows.map((r) => <div key={r[0]} className="grid md:grid-cols-[1fr_1.15fr_1fr_1.3fr] gap-2 md:gap-6 py-6 border-b border-border items-center"><span className="text-muted">{r[0]}</span><strong className="text-xl">{r[1]}</strong><span className="text-primary mono text-xs uppercase">{r[2]}</span><strong className="text-xl">{r[3]}</strong></div>)}</div></div></section> }

function Workflow() { const steps = [['01','Log what came in','Orders, tips, bonuses. Keep moving.'],['02','Subtract what went out','Gas, tolls, maintenance, all the quiet costs.'],['03','See what you actually kept','Profit, hourly rate, and goal progress—live.']]; return <section id="how" className="scroll-smooth-anchor py-24 md:py-32 bg-surface/50 border-y border-border"><div className="max-w-6xl mx-auto px-5"><SectionLabel>Three steps. No spreadsheet.</SectionLabel><h2 className="text-5xl md:text-7xl uppercase font-black max-w-3xl">Turn a night of orders into one honest number.</h2><div className="mt-14 grid md:grid-cols-3 gap-4">{steps.map(s=><div key={s[0]} className="border border-border bg-card p-7 min-h-56"><span className="mono text-primary">{s[0]}</span><h3 className="text-3xl uppercase font-black mt-12">{s[1]}</h3><p className="text-muted mt-2">{s[2]}</p></div>)}</div></div></section> }

function Outcomes() { return <section id="features" className="scroll-smooth-anchor py-24 md:py-32"><div className="max-w-6xl mx-auto px-5"><div className="max-w-2xl"><SectionLabel>What changes</SectionLabel><h2 className="text-5xl md:text-7xl uppercase font-black leading-[.9]">Work smarter<br />before you drive longer.</h2></div><div className="mt-14 grid md:grid-cols-2 lg:grid-cols-3 gap-px bg-border border border-border">{LANDING_FEATURES.map(f=><div key={f.title} className="bg-bg p-7 min-h-52 hover:bg-card transition-colors"><span className="mono text-primary">{f.icon}</span><h3 className="text-2xl uppercase font-black mt-10">{f.title}</h3><p className="text-muted mt-2 text-sm leading-relaxed">{f.body}</p></div>)}</div></div></section> }

function Personas() { const data=[['The full-time driver','Track your weekly income target and know whether you are on pace.'],['The weekend dasher','See whether your side hustle is truly profitable after expenses.'],['The multi-apper','Combine every delivery app and custom gig in one dashboard.'],['The goal chaser','Know exactly how close you are to rent, bills, or savings.']]; return <section className="py-24 md:py-32 bg-orange/10 border-y border-border"><div className="max-w-6xl mx-auto px-5"><SectionLabel>Built for how you actually work</SectionLabel><div className="grid md:grid-cols-2 gap-x-14">{data.map((x,i)=><div key={x[0]} className="py-7 border-b border-border flex gap-5"><span className="mono text-primary">0{i+1}</span><div><h3 className="text-3xl uppercase font-black">{x[0]}</h3><p className="text-muted mt-2 max-w-md">{x[1]}</p></div></div>)}</div></div></section> }

function Calculator() { const [values,setValues]=useState({earnings:220,gas:28,other:12,hours:8}); const profit=values.earnings-values.gas-values.other; const hourlyRate=values.hours>0?profit/values.hours:0; const update=(k:string,v:string)=>setValues(x=>({...x,[k]:Number(v)||0})); return <section id="calculator" className="py-24 md:py-32"><div className="max-w-5xl mx-auto px-5"><div className="grid md:grid-cols-[.8fr_1.2fr] gap-10 items-start"><div><SectionLabel>The honest math</SectionLabel><h2 className="text-5xl md:text-6xl uppercase font-black leading-[.9]">What did you actually make today?</h2><p className="text-muted mt-5">Earnings Ninja calculates this for you every day.</p></div><div className="bg-card border border-border p-6 md:p-9"><div className="grid sm:grid-cols-2 gap-5">{[['earnings','Total gig earnings'],['gas','Gas'],['other','Other expenses'],['hours','Hours worked']].map(([k,label])=><label key={k} className="block"><span className="mono text-[10px] uppercase text-muted">{label}</span><div className="flex items-center mt-2 border-b border-border"><span className="text-primary font-bold">{k==='hours'?'':'$'}</span><input type="number" value={values[k as keyof typeof values]} onChange={e=>update(k,e.target.value)} className="w-full bg-transparent px-2 py-2 text-2xl font-bold outline-none" /></div></label>)}</div><div className="mt-9 pt-7 border-t border-border grid sm:grid-cols-2 gap-6"><div className="min-w-0"><div className="mono text-xs uppercase text-muted">Actual profit</div><div className={`text-4xl lg:text-5xl font-black tracking-tight tabular-nums mt-1 ${profit<0?'text-red':'text-primary'}`}>{profit<0?'−':' '}${Math.abs(profit).toFixed(2)}</div></div><div className="min-w-0"><div className="mono text-xs uppercase text-muted">Real hourly rate</div><div className={`text-4xl lg:text-5xl font-black tracking-tight tabular-nums mt-1 ${hourlyRate<0?'text-red':'text-white'}`}>{hourlyRate<0?'−':' '}${Math.abs(hourlyRate).toFixed(2)}</div></div></div></div></div></div></section> }

function Pricing(){return <section className="py-24 md:py-32 bg-surface/50 border-y border-border"><div className="max-w-3xl mx-auto px-5 text-center"><SectionLabel>Start free</SectionLabel><h2 className="text-5xl md:text-7xl uppercase font-black">Your numbers belong to you.</h2><p className="text-muted text-lg mt-5">Core tracking is free forever. Pro adds advanced analytics, tax-ready exports, AI suggestions, and automatic imports for $2.99/mo or $29.99/yr.</p><div className="mt-8"><UpgradeButton label="Start tracking for free" /></div></div></section>}

function Faq(){return <section id="faq" className="scroll-smooth-anchor py-24 md:py-32"><div className="max-w-3xl mx-auto px-5"><SectionLabel>Questions drivers ask</SectionLabel><h2 className="text-5xl md:text-7xl uppercase font-black">No fine print energy.</h2><div className="mt-10 space-y-3">{FAQS.slice(0,6).map(x=><FaqItem key={x.q} {...x}/>)}</div></div></section>}
function FaqItem({q,a}:{q:string;a:string}){const [open,setOpen]=useState(false);const panelId=`faq-${q.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}`;return <div className="border-b border-border"><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls={panelId} className="w-full py-5 flex justify-between text-left font-bold text-lg">{q}<span className="text-primary text-2xl" aria-hidden>{open?'−':'+'}</span></button>{open&&<div id={panelId} role="region" className="pb-5 text-muted leading-relaxed"><p>{a}</p></div>}</div>}
function Final(){return <section className="py-28 md:py-40 bg-primary text-bg"><div className="max-w-4xl mx-auto px-5 text-center"><h2 className="text-6xl md:text-8xl uppercase font-black leading-[.85]">Know when to keep going—and when to go home.</h2><p className="mt-7 text-lg max-w-xl mx-auto">Stop confusing revenue with profit. Start tracking what your shift was really worth.</p><div className="mt-8"><WaitlistForm source="landing-footer" className="mx-auto" /></div></div></section>}